### ISSUE TITLE
Cannot export Typst when using packages

### ISSUE THREAD

**Issue by riccardoratta** [jgm/typst-hs#62]
**Explain the problem.**

Having this simple Typst file with this content:

```typst
#import "@preview/cetz:0.3.2"

= Introduction

Hello *world*.
```

And compiling with Typst

```console
typst compile main.typ
```

I'm however unable to convert it to LaTeX with Pandoc

```console
pandoc main.typ -s -o main.tex 
```

Because it says:

```console
pandoc: ./Users/riccardo/Library/Caches/typst/packages/preview/cetz/0.3.2/src/lib.typ: withBinaryFile: does not exist (No such file or directory)
HasCallStack backtrace:
  collectBacktraces, called at libraries/ghc-internal/src/GHC/Internal/Exception.hs:92:13 in ghc-internal:GHC.Internal.Exception
  toExceptionWithBacktrace, called at libraries/ghc-internal/src/GHC/Internal/IO.hs:260:11 in ghc-internal:GHC.Internal.IO
  throwIO, called at libraries/ghc-internal/src/GHC/Internal/IO/Exception.hs:315:19 in ghc-internal:GHC.Internal.IO.Exception
  ioException, called at libraries/ghc-internal/src/GHC/Internal/IO/Exception.hs:319:20 in ghc-internal:GHC.Internal.IO.Exception
```

The file exists at `/Users/riccardo/Library/Caches/typst/packages/preview/cetz/0.3.2/src/lib.typ`, but not at `./Users/riccardo/Library/Caches/typst/packages/preview/cetz/0.3.2/src/lib.typ` (notice the dot before the path).

**Pandoc version?**

- Pandoc 3.6.3
- Typst 0.12.0

Tried on macOS 15.3 and Ubuntu 22.04.4

**Comment by jgm** [comment]
I think I've fixed the problem.  I'll update pandoc to use this code, and you'll be able to test with the next nightly.

**Comment by riccardoratta** [comment]
> Can you try with the released binary for pandoc 3.6.2 to see if this is a regression?

In 3.6.2 I don't see the problem. Thanks.

**Comment by Mesteery** [comment]
The error is back with pandoc@3.6.3: `pandoc: ./Users/x/Library/Caches/typst/packages/preview/ctheorems/1.1.3/lib.typ: withBinaryFile: does not exist (No such file or directory)`

**Comment by jgm** [comment]
You probably just need to compile with `typst c` -- which will cause the package to be downloaded.  Pandoc won't download  the package from the typst package repository, but it knows how to find it if typst has already downloaded it.

**Comment by Mesteery** [comment]
The package is already downloaded, and the file exists and I compiled using `typst c` many times.

**Comment by jgm** [comment]
Looks like the fix to this issue is committed but not yet in a released version of this library (or in pandoc). It will be fixed in the next pandoc release, or you can try a pandoc nightly.
